site_name: signalsaurus
site_author: jlazear
site_description: Convenience structures for playing with signal processing

theme:
  name: mkdocs
  color_mode: auto
  user_color_mode_toggle: true
  locale: en

nav:
  - Home: index.md
